eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/
server:
  port: 9007
spring:
  application:
    name: liufu-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: liufu-ribbon
    api-b:
      path: /api-b/**
      serviceId: liufu-feign